export const mvpContracts = [
  { method: "POST", path: "/auth/send-otp", owner: "auth" },
  { method: "POST", path: "/auth/verify-otp", owner: "auth" },
  { method: "GET", path: "/auth/me", owner: "auth" },
  { method: "GET", path: "/farmer/profile", owner: "farmer" },
  { method: "PUT", path: "/farmer/profile", owner: "farmer" },
  { method: "POST", path: "/farmer/plots", owner: "farmer" },
  { method: "POST", path: "/farmer/crops", owner: "farmer" },
  { method: "POST", path: "/farmer/crops/{crop_id}/ready", owner: "farmer" },
  { method: "POST", path: "/agent/farmer", owner: "agent" },
  { method: "POST", path: "/agent/crop-verification", owner: "agent" },
  { method: "POST", path: "/agent/transport-request", owner: "agent" },
  { method: "GET", path: "/transporter/jobs", owner: "transporter" },
  { method: "POST", path: "/transporter/jobs/{job_id}/accept", owner: "transporter" },
  { method: "POST", path: "/transporter/jobs/{job_id}/start", owner: "transporter" },
  { method: "POST", path: "/transporter/jobs/{job_id}/pickup", owner: "transporter" },
  { method: "POST", path: "/transporter/jobs/{job_id}/deliver", owner: "transporter" },
  { method: "GET", path: "/marketplace/lots", owner: "marketplace" },
  { method: "POST", path: "/marketplace/create-lot", owner: "marketplace" },
  { method: "POST", path: "/buyer/orders", owner: "marketplace" },
  { method: "GET", path: "/storage/list", owner: "storage" },
  { method: "POST", path: "/storage/book", owner: "storage" },
  { method: "GET", path: "/notifications", owner: "notification" },
  { method: "GET", path: "/admin/dashboard", owner: "admin" }
];
